### ISSUE TITLE
LEMBRETE: Adicionar tópico "edicao5" tanto neste repositório quanto no de backend

### ISSUE THREAD

**Issue by herlocksholmes1888** [eduardodarocha/squad-21-frontend#7]
O Guilherme enviou no canal de comunicados que além de um tópico voltado ao Programa de Formação, os repositórios deveriam ter também o tópico que identificasse a edição do projeto. Enviando esse aviso aqui caso eu me esqueça de comentar na nossa daily mais tarde

**Comment by eduardodarocha** [comment]
Já adicionei.
